
import os
os.system('clear')
import numpy as np

# Problem 2
# =========
#    Each new term in the Fibonacci sequence is generated by adding the
#    previous two terms. By starting with 1 and 2, the first 10 terms will be:
#                      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#    By considering the terms in the Fibonacci sequence whose values do not
#    exceed four million, find the sum of the even-valued terms.

f = []
f.append(1)
f.append(2)
Sum = f[1]
itr = 2

while True:
    f.append(f[itr - 1] + f[itr - 2])

    if(f[itr] > 4000000): 
        break

    if(f[itr] % 2 == 0):
        Sum += f[itr]

    itr += 1


print("Sum = ", Sum)